--
-- PostgreSQL database dump
--

\restrict JfXny4TvVB0F2ZDYJWna3vfa3e8HP6QEusuUD5GG1SM7KGIdIPLaFbbqU4Qn0so

-- Dumped from database version 15.15 (Homebrew)
-- Dumped by pg_dump version 15.15 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY karbs.train_schedule DROP CONSTRAINT IF EXISTS fks7d3u9r1l4jpjjmxoutqjuk0j;
ALTER TABLE IF EXISTS ONLY karbs.booking DROP CONSTRAINT IF EXISTS fkovmspa7ois2xb4euariyvsqot;
ALTER TABLE IF EXISTS ONLY karbs.booking DROP CONSTRAINT IF EXISTS fkjhy1r09yhmiirojky5stek02q;
ALTER TABLE IF EXISTS ONLY karbs.train_schedule DROP CONSTRAINT IF EXISTS fkievh47dn31fxyth9oc0sactio;
ALTER TABLE IF EXISTS ONLY karbs.booking DROP CONSTRAINT IF EXISTS fkhavlocbsva2rs907x3obsdg3d;
ALTER TABLE IF EXISTS ONLY karbs.booked_seat DROP CONSTRAINT IF EXISTS fkh3voh6n2e83so0tyr02mc7hoa;
ALTER TABLE IF EXISTS ONLY karbs.booking DROP CONSTRAINT IF EXISTS fk7udbel7q86k041591kj6lfmvw;
ALTER TABLE IF EXISTS ONLY karbs.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY karbs.train_schedule DROP CONSTRAINT IF EXISTS train_schedule_pkey;
ALTER TABLE IF EXISTS ONLY karbs.train DROP CONSTRAINT IF EXISTS train_pkey;
ALTER TABLE IF EXISTS ONLY karbs.station DROP CONSTRAINT IF EXISTS station_station_code_key;
ALTER TABLE IF EXISTS ONLY karbs.station DROP CONSTRAINT IF EXISTS station_pkey;
ALTER TABLE IF EXISTS ONLY karbs.booking DROP CONSTRAINT IF EXISTS booking_pkey;
ALTER TABLE IF EXISTS ONLY karbs.booked_seat DROP CONSTRAINT IF EXISTS booked_seat_pkey;
DROP TABLE IF EXISTS karbs.users;
DROP TABLE IF EXISTS karbs.train_schedule;
DROP TABLE IF EXISTS karbs.train;
DROP TABLE IF EXISTS karbs.station;
DROP TABLE IF EXISTS karbs.booking;
DROP TABLE IF EXISTS karbs.booked_seat;
DROP SCHEMA IF EXISTS karbs;
--
-- Name: karbs; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA karbs;


ALTER SCHEMA karbs OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booked_seat; Type: TABLE; Schema: karbs; Owner: postgres
--

CREATE TABLE karbs.booked_seat (
    from_seq integer NOT NULL,
    seat_number integer NOT NULL,
    to_seq integer NOT NULL,
    booking_id bigint,
    seat_id bigint NOT NULL,
    coach_type character varying(255)
);


ALTER TABLE karbs.booked_seat OWNER TO postgres;

--
-- Name: booked_seat_seat_id_seq; Type: SEQUENCE; Schema: karbs; Owner: postgres
--

ALTER TABLE karbs.booked_seat ALTER COLUMN seat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME karbs.booked_seat_seat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking; Type: TABLE; Schema: karbs; Owner: postgres
--

CREATE TABLE karbs.booking (
    journey_date date,
    booking_id bigint NOT NULL,
    dest_station_id bigint,
    source_station_id bigint,
    train_id bigint,
    user_id bigint,
    booking_status character varying(255)
);


ALTER TABLE karbs.booking OWNER TO postgres;

--
-- Name: booking_booking_id_seq; Type: SEQUENCE; Schema: karbs; Owner: postgres
--

ALTER TABLE karbs.booking ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME karbs.booking_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: station; Type: TABLE; Schema: karbs; Owner: postgres
--

CREATE TABLE karbs.station (
    latitude double precision,
    longitude double precision,
    station_id bigint NOT NULL,
    city character varying(255),
    station_code character varying(255),
    station_name character varying(255)
);


ALTER TABLE karbs.station OWNER TO postgres;

--
-- Name: station_station_id_seq; Type: SEQUENCE; Schema: karbs; Owner: postgres
--

ALTER TABLE karbs.station ALTER COLUMN station_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME karbs.station_station_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: train; Type: TABLE; Schema: karbs; Owner: postgres
--

CREATE TABLE karbs.train (
    total_seats_per_coach integer NOT NULL,
    train_id bigint NOT NULL,
    train_name character varying(255),
    train_number character varying(255)
);


ALTER TABLE karbs.train OWNER TO postgres;

--
-- Name: train_schedule; Type: TABLE; Schema: karbs; Owner: postgres
--

CREATE TABLE karbs.train_schedule (
    arrival_time time(0) without time zone,
    departure_time time(0) without time zone,
    distance_from_start_km integer NOT NULL,
    stop_sequence integer NOT NULL,
    schedule_id bigint NOT NULL,
    station_id bigint,
    train_id bigint
);


ALTER TABLE karbs.train_schedule OWNER TO postgres;

--
-- Name: train_schedule_schedule_id_seq; Type: SEQUENCE; Schema: karbs; Owner: postgres
--

ALTER TABLE karbs.train_schedule ALTER COLUMN schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME karbs.train_schedule_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: train_train_id_seq; Type: SEQUENCE; Schema: karbs; Owner: postgres
--

ALTER TABLE karbs.train ALTER COLUMN train_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME karbs.train_train_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: karbs; Owner: postgres
--

CREATE TABLE karbs.users (
    user_id bigint NOT NULL,
    password character varying(255),
    role character varying(255),
    username character varying(255),
    email character varying(255),
    full_name character varying(255)
);


ALTER TABLE karbs.users OWNER TO postgres;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: karbs; Owner: postgres
--

ALTER TABLE karbs.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME karbs.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: booked_seat; Type: TABLE DATA; Schema: karbs; Owner: postgres
--

COPY karbs.booked_seat (from_seq, seat_number, to_seq, booking_id, seat_id, coach_type) FROM stdin;
\.


--
-- Data for Name: booking; Type: TABLE DATA; Schema: karbs; Owner: postgres
--

COPY karbs.booking (journey_date, booking_id, dest_station_id, source_station_id, train_id, user_id, booking_status) FROM stdin;
\.


--
-- Data for Name: station; Type: TABLE DATA; Schema: karbs; Owner: postgres
--

COPY karbs.station (latitude, longitude, station_id, city, station_code, station_name) FROM stdin;
12.9716	77.5946	1	Bengaluru	SBC	KSR Bengaluru
12.3118	76.6548	2	Mysuru	MYS	Mysuru Jn
15.3647	75.124	3	Hubballi	UBL	Hubballi Jn
12.87	74.88	4	Mangaluru	MAQ	Mangaluru Ctrl
14.82	74.13	5	Karwar	KAWR	Karwar
13.33	77.1	6	Tumakuru	TK	Tumakuru
13.31	76.25	7	Arsikere	ASK	Arsikere Jn
14.46	75.92	8	Davangere	DVG	Davangere
14.51	75.8	9	Harihar	HRR	Harihar
14.79	75.4	10	Haveri	HVR	Haveri
15.8497	74.4977	11	Belagavi	BGM	Belagavi
15.1394	76.9214	12	Ballari	BAY	Ballari Jn
15.2689	76.3909	13	Hosapete	HPT	Hosapete Jn
15.42	75.62	14	Gadag	GDG	Gadag Jn
16.8302	75.71	15	Vijayapura	BJP	Vijayapura
17.3297	76.8343	16	Kalaburagi	GR	Kalaburagi
17.05	76.98	17	Wadi	WADI	Wadi Jn
16.2	77.36	18	Raichur	RC	Raichur
17.87	76.95	19	Basavakalyan	BSK	Basavakalyan
17.91	77.5	20	Bidar	BIDR	Bidar
13	76.1	21	Hassan	HAS	Hassan Jn
12.94	75.78	22	Sakleshpur	SKLR	Sakleshpur
12.66	75.56	23	Subrahmanya	SBHR	Subrahmanya Rd
13.34	74.74	24	Udupi	UD	Udupi
13.62	74.69	25	Kundapura	KUDA	Kundapura
13.96	74.56	26	Bhatkal	BTJL	Bhatkal
14.54	74.31	27	Gokarna	GOK	Gokarna Rd
14.81	76.22	28	Kotturu	KTY	Kotturu
14.22	76.4	29	Chitradurga	CTA	Chitradurga
13.62	75.96	30	Birur	RRB	Birur Jn
\.


--
-- Data for Name: train; Type: TABLE DATA; Schema: karbs; Owner: postgres
--

COPY karbs.train (total_seats_per_coach, train_id, train_name, train_number) FROM stdin;
60	1	INT-A Express 1	12178
60	2	INT-A Express 2	11495
60	3	INT-A Express 3	15510
60	4	INT-A Express 4	11323
60	5	INT-A Express 5	13152
60	6	INT-A Express 6	11706
60	7	INT-A Express 7	11712
60	8	INT-A Express 8	14281
60	9	INT-A Express 9	13594
60	10	INT-A Express 10	11632
60	11	INT-A Express 11	17682
60	12	INT-A Express 12	18251
60	13	INT-A Express 13	17344
60	14	INT-A Express 14	16400
60	15	INT-A Express 15	10549
60	16	INT-A Express 16	17354
60	17	INT-A Express 17	13727
60	18	INT-A Express 18	15624
60	19	INT-A Express 19	14197
60	20	INT-A Express 20	15663
60	21	CST-B Express 1	10552
60	22	CST-B Express 2	15994
60	23	CST-B Express 3	16511
60	24	CST-B Express 4	14170
60	25	CST-B Express 5	18997
60	26	CST-B Express 6	10594
60	27	CST-B Express 7	18443
60	28	CST-B Express 8	13117
60	29	CST-B Express 9	14501
60	30	CST-B Express 10	16455
60	31	CST-B Express 11	10728
60	32	CST-B Express 12	15247
60	33	CST-B Express 13	15769
60	34	CST-B Express 14	10331
60	35	CST-B Express 15	18679
60	36	NTH-C Express 1	15897
60	37	NTH-C Express 2	17383
60	38	NTH-C Express 3	12697
60	39	NTH-C Express 4	12687
60	40	NTH-C Express 5	18398
60	41	NTH-C Express 6	11012
60	42	NTH-C Express 7	14835
60	43	NTH-C Express 8	10263
60	44	NTH-C Express 9	11179
60	45	NTH-C Express 10	13047
60	46	NTH-C Express 11	14572
60	47	NTH-C Express 12	13355
60	48	NTH-C Express 13	10137
60	49	NTH-C Express 14	11896
60	50	NTH-C Express 15	12808
40	51	Pass-HAS-GDG	08575
40	52	Pass-BJP-BIDR	07136
40	53	Pass-BJP-KTY	02658
40	54	Pass-GR-WADI	01231
40	55	Pass-KAWR-KUDA	03699
40	56	Pass-SKLR-GDG	08094
40	57	Pass-BTJL-KTY	06445
40	58	Pass-GOK-UBL	08266
40	59	Pass-KAWR-HPT	04198
40	60	Pass-HRR-BGM	06899
40	61	Pass-BTJL-CTA	05883
40	62	Pass-UBL-HPT	07962
40	63	Pass-ASK-CTA	02394
40	64	Pass-HRR-BGM	07518
40	65	Pass-MYS-HAS	08275
40	66	Pass-KAWR-GDG	03615
40	67	Pass-BTJL-KAWR	01529
40	68	Pass-BAY-ASK	02646
40	69	Pass-BJP-HRR	07646
40	70	Pass-HRR-RRB	06508
40	71	Pass-HRR-ASK	04537
40	72	Pass-WADI-GDG	05636
40	73	Pass-UD-HAS	03307
40	74	Pass-WADI-RC	07998
40	75	Pass-ASK-SBHR	06311
40	76	Pass-ASK-GDG	00654
40	77	Pass-BAY-HPT	05863
40	78	Pass-SKLR-HAS	07560
40	79	Pass-KTY-SBC	02470
40	80	Pass-KAWR-BGM	04962
40	81	Pass-UBL-RRB	01949
40	82	Pass-KAWR-HPT	03308
40	83	Pass-UBL-WADI	02775
40	84	Pass-HVR-HAS	07250
40	85	Pass-GR-UBL	01390
40	86	Pass-MYS-HRR	05727
40	87	Pass-SBC-SBHR	08306
40	88	Pass-BTJL-SKLR	05271
40	89	Pass-SBC-HPT	02745
40	90	Pass-WADI-GDG	08058
40	91	Pass-BGM-KTY	03191
40	92	Pass-SBHR-HRR	04880
40	93	Pass-BGM-UD	03023
40	94	Pass-KTY-SBHR	08554
40	95	Pass-TK-MYS	05101
40	96	Pass-KUDA-SBHR	03949
40	97	Pass-SKLR-ASK	00654
40	98	Pass-WADI-BJP	07099
40	99	Pass-MAQ-HAS	00777
40	100	Pass-BTJL-UD	05549
\.


--
-- Data for Name: train_schedule; Type: TABLE DATA; Schema: karbs; Owner: postgres
--

COPY karbs.train_schedule (arrival_time, departure_time, distance_from_start_km, stop_sequence, schedule_id, station_id, train_id) FROM stdin;
06:00:00	06:05:00	0	1	1	1	1
07:11:00	07:16:00	66	2	2	6	1
08:47:00	08:52:00	157	3	3	7	1
11:04:00	11:09:00	289	4	4	8	1
12:15:00	12:20:00	355	5	5	10	1
13:30:00	13:30:00	425	6	6	3	1
07:00:00	07:05:00	0	1	7	1	2
08:11:00	08:16:00	66	2	8	6	2
09:47:00	09:52:00	157	3	9	7	2
12:04:00	12:09:00	289	4	10	8	2
13:15:00	13:20:00	355	5	11	10	2
14:30:00	14:30:00	425	6	12	3	2
08:00:00	08:05:00	0	1	13	1	3
09:11:00	09:16:00	66	2	14	6	3
10:47:00	10:52:00	157	3	15	7	3
13:04:00	13:09:00	289	4	16	8	3
14:15:00	14:20:00	355	5	17	10	3
15:30:00	15:30:00	425	6	18	3	3
09:00:00	09:05:00	0	1	19	1	4
10:11:00	10:16:00	66	2	20	6	4
11:47:00	11:52:00	157	3	21	7	4
14:04:00	14:09:00	289	4	22	8	4
15:15:00	15:20:00	355	5	23	10	4
16:30:00	16:30:00	425	6	24	3	4
10:00:00	10:05:00	0	1	25	1	5
11:11:00	11:16:00	66	2	26	6	5
12:47:00	12:52:00	157	3	27	7	5
15:04:00	15:09:00	289	4	28	8	5
16:15:00	16:20:00	355	5	29	10	5
17:30:00	17:30:00	425	6	30	3	5
11:00:00	11:05:00	0	1	31	1	6
12:11:00	12:16:00	66	2	32	6	6
13:47:00	13:52:00	157	3	33	7	6
16:04:00	16:09:00	289	4	34	8	6
17:15:00	17:20:00	355	5	35	10	6
18:30:00	18:30:00	425	6	36	3	6
12:00:00	12:05:00	0	1	37	1	7
13:11:00	13:16:00	66	2	38	6	7
14:47:00	14:52:00	157	3	39	7	7
17:04:00	17:09:00	289	4	40	8	7
18:15:00	18:20:00	355	5	41	10	7
19:30:00	19:30:00	425	6	42	3	7
13:00:00	13:05:00	0	1	43	1	8
14:11:00	14:16:00	66	2	44	6	8
15:47:00	15:52:00	157	3	45	7	8
18:04:00	18:09:00	289	4	46	8	8
19:15:00	19:20:00	355	5	47	10	8
20:30:00	20:30:00	425	6	48	3	8
14:00:00	14:05:00	0	1	49	1	9
15:11:00	15:16:00	66	2	50	6	9
16:47:00	16:52:00	157	3	51	7	9
19:04:00	19:09:00	289	4	52	8	9
20:15:00	20:20:00	355	5	53	10	9
21:30:00	21:30:00	425	6	54	3	9
15:00:00	15:05:00	0	1	55	1	10
16:11:00	16:16:00	66	2	56	6	10
17:47:00	17:52:00	157	3	57	7	10
20:04:00	20:09:00	289	4	58	8	10
21:15:00	21:20:00	355	5	59	10	10
22:30:00	22:30:00	425	6	60	3	10
16:00:00	16:05:00	0	1	61	1	11
17:11:00	17:16:00	66	2	62	6	11
18:47:00	18:52:00	157	3	63	7	11
21:04:00	21:09:00	289	4	64	8	11
22:15:00	22:20:00	355	5	65	10	11
23:30:00	23:30:00	425	6	66	3	11
17:00:00	17:05:00	0	1	67	1	12
18:11:00	18:16:00	66	2	68	6	12
19:47:00	19:52:00	157	3	69	7	12
22:04:00	22:09:00	289	4	70	8	12
23:15:00	23:20:00	355	5	71	10	12
00:30:00	00:30:00	425	6	72	3	12
18:00:00	18:05:00	0	1	73	1	13
19:11:00	19:16:00	66	2	74	6	13
20:47:00	20:52:00	157	3	75	7	13
23:04:00	23:09:00	289	4	76	8	13
00:15:00	00:20:00	355	5	77	10	13
01:30:00	01:30:00	425	6	78	3	13
19:00:00	19:05:00	0	1	79	1	14
20:11:00	20:16:00	66	2	80	6	14
21:47:00	21:52:00	157	3	81	7	14
00:04:00	00:09:00	289	4	82	8	14
01:15:00	01:20:00	355	5	83	10	14
02:30:00	02:30:00	425	6	84	3	14
20:00:00	20:05:00	0	1	85	1	15
21:11:00	21:16:00	66	2	86	6	15
22:47:00	22:52:00	157	3	87	7	15
01:04:00	01:09:00	289	4	88	8	15
02:15:00	02:20:00	355	5	89	10	15
03:30:00	03:30:00	425	6	90	3	15
21:00:00	21:05:00	0	1	91	1	16
22:11:00	22:16:00	66	2	92	6	16
23:47:00	23:52:00	157	3	93	7	16
02:04:00	02:09:00	289	4	94	8	16
03:15:00	03:20:00	355	5	95	10	16
04:30:00	04:30:00	425	6	96	3	16
22:00:00	22:05:00	0	1	97	1	17
23:11:00	23:16:00	66	2	98	6	17
00:47:00	00:52:00	157	3	99	7	17
03:04:00	03:09:00	289	4	100	8	17
04:15:00	04:20:00	355	5	101	10	17
05:30:00	05:30:00	425	6	102	3	17
23:00:00	23:05:00	0	1	103	1	18
00:11:00	00:16:00	66	2	104	6	18
01:47:00	01:52:00	157	3	105	7	18
04:04:00	04:09:00	289	4	106	8	18
05:15:00	05:20:00	355	5	107	10	18
06:30:00	06:30:00	425	6	108	3	18
00:00:00	00:05:00	0	1	109	1	19
01:11:00	01:16:00	66	2	110	6	19
02:47:00	02:52:00	157	3	111	7	19
05:04:00	05:09:00	289	4	112	8	19
06:15:00	06:20:00	355	5	113	10	19
07:30:00	07:30:00	425	6	114	3	19
01:00:00	01:05:00	0	1	115	1	20
02:11:00	02:16:00	66	2	116	6	20
03:47:00	03:52:00	157	3	117	7	20
06:04:00	06:09:00	289	4	118	8	20
07:15:00	07:20:00	355	5	119	10	20
08:30:00	08:30:00	425	6	120	3	20
05:00:00	05:05:00	0	1	121	1	21
08:40:00	08:45:00	161	2	122	21	21
09:31:00	09:36:00	196	3	123	22	21
12:17:00	12:22:00	316	4	124	24	21
16:17:00	16:17:00	492	5	125	5	21
06:00:00	06:05:00	0	1	126	1	22
09:40:00	09:45:00	161	2	127	21	22
10:31:00	10:36:00	196	3	128	22	22
13:17:00	13:22:00	316	4	129	24	22
17:17:00	17:17:00	492	5	130	5	22
07:00:00	07:05:00	0	1	131	1	23
10:40:00	10:45:00	161	2	132	21	23
11:31:00	11:36:00	196	3	133	22	23
14:17:00	14:22:00	316	4	134	24	23
18:17:00	18:17:00	492	5	135	5	23
08:00:00	08:05:00	0	1	136	1	24
11:40:00	11:45:00	161	2	137	21	24
12:31:00	12:36:00	196	3	138	22	24
15:17:00	15:22:00	316	4	139	24	24
19:17:00	19:17:00	492	5	140	5	24
09:00:00	09:05:00	0	1	141	1	25
12:40:00	12:45:00	161	2	142	21	25
13:31:00	13:36:00	196	3	143	22	25
16:17:00	16:22:00	316	4	144	24	25
20:17:00	20:17:00	492	5	145	5	25
10:00:00	10:05:00	0	1	146	1	26
13:40:00	13:45:00	161	2	147	21	26
14:31:00	14:36:00	196	3	148	22	26
17:17:00	17:22:00	316	4	149	24	26
21:17:00	21:17:00	492	5	150	5	26
11:00:00	11:05:00	0	1	151	1	27
14:40:00	14:45:00	161	2	152	21	27
15:31:00	15:36:00	196	3	153	22	27
18:17:00	18:22:00	316	4	154	24	27
22:17:00	22:17:00	492	5	155	5	27
12:00:00	12:05:00	0	1	156	1	28
15:40:00	15:45:00	161	2	157	21	28
16:31:00	16:36:00	196	3	158	22	28
19:17:00	19:22:00	316	4	159	24	28
23:17:00	23:17:00	492	5	160	5	28
13:00:00	13:05:00	0	1	161	1	29
16:40:00	16:45:00	161	2	162	21	29
17:31:00	17:36:00	196	3	163	22	29
20:17:00	20:22:00	316	4	164	24	29
00:17:00	00:17:00	492	5	165	5	29
14:00:00	14:05:00	0	1	166	1	30
17:40:00	17:45:00	161	2	167	21	30
18:31:00	18:36:00	196	3	168	22	30
21:17:00	21:22:00	316	4	169	24	30
01:17:00	01:17:00	492	5	170	5	30
15:00:00	15:05:00	0	1	171	1	31
18:40:00	18:45:00	161	2	172	21	31
19:31:00	19:36:00	196	3	173	22	31
22:17:00	22:22:00	316	4	174	24	31
02:17:00	02:17:00	492	5	175	5	31
16:00:00	16:05:00	0	1	176	1	32
19:40:00	19:45:00	161	2	177	21	32
20:31:00	20:36:00	196	3	178	22	32
23:17:00	23:22:00	316	4	179	24	32
03:17:00	03:17:00	492	5	180	5	32
17:00:00	17:05:00	0	1	181	1	33
20:40:00	20:45:00	161	2	182	21	33
21:31:00	21:36:00	196	3	183	22	33
00:17:00	00:22:00	316	4	184	24	33
04:17:00	04:17:00	492	5	185	5	33
18:00:00	18:05:00	0	1	186	1	34
21:40:00	21:45:00	161	2	187	21	34
22:31:00	22:36:00	196	3	188	22	34
01:17:00	01:22:00	316	4	189	24	34
05:17:00	05:17:00	492	5	190	5	34
19:00:00	19:05:00	0	1	191	1	35
22:40:00	22:45:00	161	2	192	21	35
23:31:00	23:36:00	196	3	193	22	35
02:17:00	02:22:00	316	4	194	24	35
06:17:00	06:17:00	492	5	195	5	35
07:00:00	07:05:00	0	1	196	3	36
08:03:00	08:08:00	53	2	197	14	36
09:39:00	09:44:00	137	3	198	13	36
10:47:00	10:52:00	195	4	199	12	36
13:10:00	13:15:00	321	5	200	18	36
15:44:00	15:44:00	458	6	201	16	36
08:00:00	08:05:00	0	1	202	3	37
09:03:00	09:08:00	53	2	203	14	37
10:39:00	10:44:00	137	3	204	13	37
11:47:00	11:52:00	195	4	205	12	37
14:10:00	14:15:00	321	5	206	18	37
16:44:00	16:44:00	458	6	207	16	37
09:00:00	09:05:00	0	1	208	3	38
10:03:00	10:08:00	53	2	209	14	38
11:39:00	11:44:00	137	3	210	13	38
12:47:00	12:52:00	195	4	211	12	38
15:10:00	15:15:00	321	5	212	18	38
17:44:00	17:44:00	458	6	213	16	38
10:00:00	10:05:00	0	1	214	3	39
11:03:00	11:08:00	53	2	215	14	39
12:39:00	12:44:00	137	3	216	13	39
13:47:00	13:52:00	195	4	217	12	39
16:10:00	16:15:00	321	5	218	18	39
18:44:00	18:44:00	458	6	219	16	39
11:00:00	11:05:00	0	1	220	3	40
12:03:00	12:08:00	53	2	221	14	40
13:39:00	13:44:00	137	3	222	13	40
14:47:00	14:52:00	195	4	223	12	40
17:10:00	17:15:00	321	5	224	18	40
19:44:00	19:44:00	458	6	225	16	40
12:00:00	12:05:00	0	1	226	3	41
13:03:00	13:08:00	53	2	227	14	41
14:39:00	14:44:00	137	3	228	13	41
15:47:00	15:52:00	195	4	229	12	41
18:10:00	18:15:00	321	5	230	18	41
20:44:00	20:44:00	458	6	231	16	41
13:00:00	13:05:00	0	1	232	3	42
14:03:00	14:08:00	53	2	233	14	42
15:39:00	15:44:00	137	3	234	13	42
16:47:00	16:52:00	195	4	235	12	42
19:10:00	19:15:00	321	5	236	18	42
21:44:00	21:44:00	458	6	237	16	42
14:00:00	14:05:00	0	1	238	3	43
15:03:00	15:08:00	53	2	239	14	43
16:39:00	16:44:00	137	3	240	13	43
17:47:00	17:52:00	195	4	241	12	43
20:10:00	20:15:00	321	5	242	18	43
22:44:00	22:44:00	458	6	243	16	43
15:00:00	15:05:00	0	1	244	3	44
16:03:00	16:08:00	53	2	245	14	44
17:39:00	17:44:00	137	3	246	13	44
18:47:00	18:52:00	195	4	247	12	44
21:10:00	21:15:00	321	5	248	18	44
23:44:00	23:44:00	458	6	249	16	44
16:00:00	16:05:00	0	1	250	3	45
17:03:00	17:08:00	53	2	251	14	45
18:39:00	18:44:00	137	3	252	13	45
19:47:00	19:52:00	195	4	253	12	45
22:10:00	22:15:00	321	5	254	18	45
00:44:00	00:44:00	458	6	255	16	45
17:00:00	17:05:00	0	1	256	3	46
18:03:00	18:08:00	53	2	257	14	46
19:39:00	19:44:00	137	3	258	13	46
20:47:00	20:52:00	195	4	259	12	46
23:10:00	23:15:00	321	5	260	18	46
01:44:00	01:44:00	458	6	261	16	46
18:00:00	18:05:00	0	1	262	3	47
19:03:00	19:08:00	53	2	263	14	47
20:39:00	20:44:00	137	3	264	13	47
21:47:00	21:52:00	195	4	265	12	47
00:10:00	00:15:00	321	5	266	18	47
02:44:00	02:44:00	458	6	267	16	47
19:00:00	19:05:00	0	1	268	3	48
20:03:00	20:08:00	53	2	269	14	48
21:39:00	21:44:00	137	3	270	13	48
22:47:00	22:52:00	195	4	271	12	48
01:10:00	01:15:00	321	5	272	18	48
03:44:00	03:44:00	458	6	273	16	48
20:00:00	20:05:00	0	1	274	3	49
21:03:00	21:08:00	53	2	275	14	49
22:39:00	22:44:00	137	3	276	13	49
23:47:00	23:52:00	195	4	277	12	49
02:10:00	02:15:00	321	5	278	18	49
04:44:00	04:44:00	458	6	279	16	49
21:00:00	21:05:00	0	1	280	3	50
22:03:00	22:08:00	53	2	281	14	50
23:39:00	23:44:00	137	3	282	13	50
00:47:00	00:52:00	195	4	283	12	50
03:10:00	03:15:00	321	5	284	18	50
05:44:00	05:44:00	458	6	285	16	50
14:22:00	14:24:00	0	1	286	21	51
21:11:00	21:11:00	273	2	287	14	51
16:23:00	16:25:00	0	1	288	15	52
21:59:00	21:59:00	224	2	289	20	52
08:08:00	08:10:00	0	1	290	15	53
13:53:00	13:53:00	230	2	291	28	53
09:30:00	09:32:00	0	1	292	16	54
10:21:00	10:21:00	34	2	293	17	54
11:10:00	11:12:00	0	1	294	5	55
14:49:00	14:49:00	146	2	295	25	55
12:17:00	12:19:00	0	1	296	22	56
19:09:00	19:09:00	275	2	297	14	56
15:05:00	15:07:00	0	1	298	26	57
20:08:00	20:08:00	202	2	299	28	57
09:22:00	09:24:00	0	1	300	27	58
12:31:00	12:31:00	126	2	301	3	58
18:18:00	18:20:00	0	1	302	5	59
00:28:00	00:28:00	247	2	303	13	59
06:53:00	06:55:00	0	1	304	9	60
11:59:00	11:59:00	204	2	305	11	60
17:43:00	17:45:00	0	1	306	26	61
22:43:00	22:43:00	200	2	307	29	61
17:32:00	17:34:00	0	1	308	3	62
20:56:00	20:56:00	136	2	309	13	62
10:08:00	10:10:00	0	1	310	7	63
12:41:00	12:41:00	102	2	311	29	63
09:43:00	09:45:00	0	1	312	9	64
14:49:00	14:49:00	204	2	313	11	64
15:48:00	15:50:00	0	1	314	2	65
18:13:00	18:13:00	97	2	315	21	65
08:58:00	09:00:00	0	1	316	5	66
13:17:00	13:17:00	173	2	317	14	66
17:13:00	17:15:00	0	1	318	26	67
19:52:00	19:52:00	106	2	319	5	67
09:27:00	09:29:00	0	1	320	12	68
14:49:00	14:49:00	215	2	321	7	68
15:00:00	15:02:00	0	1	322	15	69
21:25:00	21:25:00	257	2	323	9	69
15:13:00	15:15:00	0	1	324	9	70
17:43:00	17:43:00	100	2	325	30	70
15:00:00	15:02:00	0	1	326	9	71
18:31:00	18:31:00	141	2	327	7	71
13:10:00	13:12:00	0	1	328	17	72
18:56:00	18:56:00	231	2	329	14	72
11:04:00	11:06:00	0	1	330	24	73
14:50:00	14:50:00	151	2	331	21	73
15:44:00	15:46:00	0	1	332	17	74
18:17:00	18:17:00	102	2	333	18	74
10:57:00	10:59:00	0	1	334	7	75
13:31:00	13:31:00	103	2	335	23	75
14:31:00	14:33:00	0	1	336	7	76
20:35:00	20:35:00	243	2	337	14	76
08:46:00	08:48:00	0	1	338	12	77
10:13:00	10:13:00	58	2	339	13	77
07:18:00	07:20:00	0	1	340	22	78
08:10:00	08:10:00	35	2	341	21	78
12:42:00	12:44:00	0	1	342	28	79
18:58:00	18:58:00	251	2	343	1	79
09:26:00	09:28:00	0	1	344	5	80
12:26:00	12:26:00	120	2	345	11	80
18:04:00	18:06:00	0	1	346	3	81
23:23:00	23:23:00	213	2	347	30	81
19:43:00	19:45:00	0	1	348	5	82
01:53:00	01:53:00	247	2	349	13	82
10:10:00	10:12:00	0	1	350	3	83
16:58:00	16:58:00	272	2	351	17	83
07:22:00	07:24:00	0	1	352	10	84
12:40:00	12:40:00	212	2	353	21	84
15:36:00	15:38:00	0	1	354	16	85
22:40:00	22:40:00	283	2	355	3	85
06:48:00	06:50:00	0	1	356	2	86
13:19:00	13:19:00	261	2	357	9	86
13:25:00	13:27:00	0	1	358	1	87
18:58:00	18:58:00	222	2	359	23	87
19:38:00	19:40:00	0	1	360	26	88
23:57:00	23:57:00	173	2	361	22	88
12:58:00	13:00:00	0	1	362	1	89
20:07:00	20:07:00	286	2	363	13	89
11:23:00	11:25:00	0	1	364	17	90
17:09:00	17:09:00	231	2	365	14	90
09:52:00	09:54:00	0	1	366	11	91
15:17:00	15:17:00	217	2	367	28	91
17:34:00	17:36:00	0	1	368	23	92
22:43:00	22:43:00	206	2	369	9	92
13:43:00	13:45:00	0	1	370	11	93
20:41:00	20:41:00	279	2	371	24	93
17:03:00	17:05:00	0	1	372	28	94
23:15:00	23:15:00	248	2	373	23	94
14:18:00	14:20:00	0	1	374	6	95
17:21:00	17:21:00	122	2	375	2	95
16:38:00	16:40:00	0	1	376	25	96
20:09:00	20:09:00	141	2	377	23	96
11:58:00	12:00:00	0	1	378	22	97
13:35:00	13:35:00	65	2	379	7	97
07:47:00	07:49:00	0	1	380	17	98
11:11:00	11:11:00	136	2	381	15	98
16:01:00	16:03:00	0	1	382	4	99
19:19:00	19:19:00	132	2	383	21	99
19:02:00	19:04:00	0	1	384	26	100
20:48:00	20:48:00	71	2	385	24	100
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: karbs; Owner: postgres
--

COPY karbs.users (user_id, password, role, username, email, full_name) FROM stdin;
4	$2a$10$.hvZkWlo0ZpFcJXYvwShz.v6T8WIic9s6adQs1hS2QJYJuEZ8Ebzq	ADMIN	rahul	rahul@gmail.com	rahul kharwar
5	$2a$10$Df.21aitpj2nhyQIdk5/VOGqM14XJCH9JSC1cVDh8xWIaCpvFuXey	USER	thilaks	thilaks1624@gmail.com	Thilak S
6	$2a$10$xWFoJCw1nyroLZppM4TrreMzyIGFnZ6NAe7wOAP8gLZ6SWSVOqMBe	USER	shreyan	shreyan@gmail.com	shreyan das
\.


--
-- Name: booked_seat_seat_id_seq; Type: SEQUENCE SET; Schema: karbs; Owner: postgres
--

SELECT pg_catalog.setval('karbs.booked_seat_seat_id_seq', 2, true);


--
-- Name: booking_booking_id_seq; Type: SEQUENCE SET; Schema: karbs; Owner: postgres
--

SELECT pg_catalog.setval('karbs.booking_booking_id_seq', 1, true);


--
-- Name: station_station_id_seq; Type: SEQUENCE SET; Schema: karbs; Owner: postgres
--

SELECT pg_catalog.setval('karbs.station_station_id_seq', 30, true);


--
-- Name: train_schedule_schedule_id_seq; Type: SEQUENCE SET; Schema: karbs; Owner: postgres
--

SELECT pg_catalog.setval('karbs.train_schedule_schedule_id_seq', 385, true);


--
-- Name: train_train_id_seq; Type: SEQUENCE SET; Schema: karbs; Owner: postgres
--

SELECT pg_catalog.setval('karbs.train_train_id_seq', 100, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: karbs; Owner: postgres
--

SELECT pg_catalog.setval('karbs.users_user_id_seq', 6, true);


--
-- Name: booked_seat booked_seat_pkey; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booked_seat
    ADD CONSTRAINT booked_seat_pkey PRIMARY KEY (seat_id);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (booking_id);


--
-- Name: station station_pkey; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.station
    ADD CONSTRAINT station_pkey PRIMARY KEY (station_id);


--
-- Name: station station_station_code_key; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.station
    ADD CONSTRAINT station_station_code_key UNIQUE (station_code);


--
-- Name: train train_pkey; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.train
    ADD CONSTRAINT train_pkey PRIMARY KEY (train_id);


--
-- Name: train_schedule train_schedule_pkey; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.train_schedule
    ADD CONSTRAINT train_schedule_pkey PRIMARY KEY (schedule_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: booking fk7udbel7q86k041591kj6lfmvw; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booking
    ADD CONSTRAINT fk7udbel7q86k041591kj6lfmvw FOREIGN KEY (user_id) REFERENCES karbs.users(user_id);


--
-- Name: booked_seat fkh3voh6n2e83so0tyr02mc7hoa; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booked_seat
    ADD CONSTRAINT fkh3voh6n2e83so0tyr02mc7hoa FOREIGN KEY (booking_id) REFERENCES karbs.booking(booking_id);


--
-- Name: booking fkhavlocbsva2rs907x3obsdg3d; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booking
    ADD CONSTRAINT fkhavlocbsva2rs907x3obsdg3d FOREIGN KEY (source_station_id) REFERENCES karbs.station(station_id);


--
-- Name: train_schedule fkievh47dn31fxyth9oc0sactio; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.train_schedule
    ADD CONSTRAINT fkievh47dn31fxyth9oc0sactio FOREIGN KEY (train_id) REFERENCES karbs.train(train_id);


--
-- Name: booking fkjhy1r09yhmiirojky5stek02q; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booking
    ADD CONSTRAINT fkjhy1r09yhmiirojky5stek02q FOREIGN KEY (dest_station_id) REFERENCES karbs.station(station_id);


--
-- Name: booking fkovmspa7ois2xb4euariyvsqot; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.booking
    ADD CONSTRAINT fkovmspa7ois2xb4euariyvsqot FOREIGN KEY (train_id) REFERENCES karbs.train(train_id);


--
-- Name: train_schedule fks7d3u9r1l4jpjjmxoutqjuk0j; Type: FK CONSTRAINT; Schema: karbs; Owner: postgres
--

ALTER TABLE ONLY karbs.train_schedule
    ADD CONSTRAINT fks7d3u9r1l4jpjjmxoutqjuk0j FOREIGN KEY (station_id) REFERENCES karbs.station(station_id);


--
-- PostgreSQL database dump complete
--

\unrestrict JfXny4TvVB0F2ZDYJWna3vfa3e8HP6QEusuUD5GG1SM7KGIdIPLaFbbqU4Qn0so

